name: Deploy Spring Boot App to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      run: |
        az acr login --name container011.azurecr.io

    - name: Build and push Docker image
      run: |
        docker build -t container011.azurecr.io/navii:latest .
        docker push container011.azurecr.io/navii:latest

    - name: Deploy to AKS
      run: |
        az aks get-credentials --resource-group navya --name kubernetes
        kubectl apply -f k8s/deployment.yml
        kubectl apply -f k8s/service.yml
        #comment
